### ISSUE TITLE
[Bug]: No value associated with key exp

### ISSUE THREAD

**Issue by juliettebee** [MasterJ93/ATProtoKit#37]
### Summary

Getting user's timeline returns an error

### Reproduction Steps

Sign in, then run `try await atProto.getTimeline()`. This also happens when running `try await safeAtproto.getSuggestedFeeds()`

### Expected Results

An error not to be thrown

### Actual Results

The follow errors are thrown:
```swift
keyNotFound(CodingKeys(stringValue: "exp", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "feeds", intValue: nil), _CodingKey(stringValue: "Index 13", intValue: 13), CodingKeys(stringValue: "creator", intValue: nil), CodingKeys(stringValue: "labels", intValue: nil), _CodingKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"exp\", intValue: nil) (\"exp\").", underlyingError: nil))
keyNotFound(CodingKeys(stringValue: "exp", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "feed", intValue: nil), _CodingKey(stringValue: "Index 3", intValue: 3), CodingKeys(stringValue: "post", intValue: nil), CodingKeys(stringValue: "author", intValue: nil), CodingKeys(stringValue: "labels", intValue: nil), _CodingKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"exp\", intValue: nil) (\"exp\").", underlyingError: nil))
```

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

Other

### Operating System Version

iOS 18.1 (22B5075a)

### ATProtoKit Version

main branch (de8c222)

### Additional Context

Thank you so much for your help!

**Comment by MasterJ93** [comment]
This is something I've been trying to fix for the past little while and it keeps popping up. I'm still looking into it.

**Comment by MasterJ93** [comment]
Wait a minute... I'm just now realizing that this was made at 7:44 PM yesterday. I think I've updated ATProtoKit by then. Please update the project and see if the issue persists.

**Comment by MasterJ93** [comment]
I've temporarily disabled the ability to see that specific property. This will be live in the next patch. I'll look into it a bit further, but the path of least resistance right now is to temporarily disable it. It'll be back in a future update.

This issue will remain open until I know it's fixed.

**Comment by juliettebee** [comment]
Sorry for such a late response! Latest commit at the time (7321b8c) fixes this issue. Thank you so much

**Comment by MasterJ93** [comment]
Great!

... however, I can't close this issue until I re-enable the property with the confidence that it won't cause any more trouble. I'll be leaving this open until then. I may ask you to see if it comes back once I do, if you don't mind.

**Comment by MasterJ93** [comment]
I pushed an update in the `develop` branch; I've reword certain parts of the project that should let the project decode and encode `exp` properly again. Let me know if it breaks. If so, I'll disable it and try a different tactic.

**Comment by MasterJ93** [comment]
I recently pushed an update to ATProtoKit (version 0.20.0) which should potentially solve this issue for good. `exp` should now be decoded and encoded properly, since I've changed the way it's being converted. I'll be closing this issue now, but if the issue appears again, please re-open the issue and I'll disable it again until I have a better, more tested fix. Thanks for reporting the issue!
