### ISSUE TITLE
[Bug]: Threaded Replies Not Handled Correctly

### ISSUE THREAD

**Issue by aaronvegh** [MasterJ93/ATProtoKit#38]
### Summary

Replies to your own posts to create a thread do not result in a properly-formatted thread on bsky.app. 

### Reproduction Steps

The API for ATProtoKit takes a string reference to the `replyTo` parameter of `createPostRecord`. When posting a collection of posts, with each set to reply to the previous post, I am supplying the previous post's identifier for each post. The first two posts of a thread will be correctly connected. The third and subsequent posts in the thread will not be connected properly on bsky.app. 

Here's a set of four posts that were intended to exist in a thread:

https://bsky.app/profile/croissantageddon.bsky.social/post/3l6vfdpuubp2u
https://bsky.app/profile/croissantageddon.bsky.social/post/3l6vfdq4mfg2v
https://bsky.app/profile/croissantageddon.bsky.social/post/3l6vfdqe7ub2k
https://bsky.app/profile/croissantageddon.bsky.social/post/3l6vfdqlftp2u

Only the first and second of these are connected as a thread.

### Expected Results

When providing a `replyTo` value I expect the chain of posts to be connected as a thread.

### Actual Results

As described above, only the first two posts in a thread are connected.

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS, Other

### Operating System Version

Mac and iOS

### ATProtoKit Version

0.18.3

### Additional Context

I've done some research into the cause of this issue. I found [this explanation](https://github.com/scripting/blue.feedland/issues/14#issuecomment-1586214930) for how replies are supposed to work. Replying requires the parent AND root identifiers. As I am supplying only the parent identifier, I was hoping ATProtoKit would do the needful and figure out the root; I note the presence of `resolveReplyReferences` which should kick that off. However, every result returned only provides the parent values. THat's why the first two posts in a thread work fine: the parent IS the root. 

So this should be resolved either by having the `resolveReplyReferences` method figure out the root, or more simply, update the API so the user can supply the root value and the parent value. I don't mind doing this in my own use case.

**Comment by MasterJ93** [comment]
I'll probably have to modify `resolveReplyReferences` so it figures that out for you. Ideally, I don't want developers to have to manually input things: the API should be giving you that information. But if you have a reason as to why manually inputing the root and parent values should be the solution, I'm open to hearing it

**Comment by aaronvegh** [comment]
To be frank, the only reason I’d support manual entry of the root ID is expediency; it’d be the quicker fix, and it would be fairly trivial to support on my end. My users are getting bitten by this now, so I’m motivated to find a solution! I was hoping you might be able to provide thoughts about whether you would look at this fix in the near term; otherwise I might hack a fix in a fork. I would definitely prefer that it be done right, though… 🫣

**Comment by MasterJ93** [comment]
I didn't realize the urgency in this. I'll put this in a higher priority, then.

**Comment by aaronvegh** [comment]
Oh! Thank you so much for your consideration. 🌈

**Comment by MasterJ93** [comment]
I'll probably have to have it where you should manually input the values for now, and then come up with a better fix later. Would you mind doing that and make a PR? If I do figure out how to fix it without needing to do that, however, then don't worry about it.

**Comment by MasterJ93** [comment]
If I change the method signature of `createPostRecord` to the following:
```swift
public func createPostRecord(
        text: String,
        locales: [Locale] = [],
        replyTo: AppBskyLexicon.Feed.PostRecord.ReplyReference? = nil,
        embed: EmbedIdentifier? = nil,
        labels: ATUnion.PostSelfLabelsUnion? = nil,
        tags: [String]? = nil,
        creationDate: Date = Date(),
        recordKey: String? = nil,
        shouldValidate: Bool? = true,
        swapCommit: String? = nil
    ) async throws -> ComAtprotoLexicon.Repository.StrongReference
```

then make it be passed onto `resolveReplyReference` accordingly, would that be too much work? If not, then this would probably be the closest solution I can quickly think of (if not _the_ solution).

**Comment by aaronvegh** [comment]
I think this could work quite well! When I want to make a post, I'm calling `createPostRecord` and getting back a `ComAtprotoLexicon.Repository.StrongReference`. I can hang onto the first post result and then track each subsequent post's result to generate the `ReplyReference`. Yes, this would work perfectly for me.

**Comment by MasterJ93** [comment]
Okay. If this isn't crossing the line of "inconvenient," then I'll make that change. I'll have that ready later today (hopefully).

**Comment by MasterJ93** [comment]
I'm going to change `resolveReplyReference` into a method where it simply checks if the reference is valid. This does mean that some of the code you've contributed would be moved around or removed, which I'm sorry to do but for the sake of fixing this bug, this is the only option until I could maybe make a way to bring it back. I apologize if this is disappointing.

**Comment by aaronvegh** [comment]
I don't mind; do what works!

**Comment by MasterJ93** [comment]
I've pushed an update to a separate branch for a fix to this. I'll merge it to `main` in a few minutes.

You can do something like this:
```swift
        do {
            let threadPost = try await atProtoBluesky.createPostRecord(
                text: "I like waffles."
            )

            print("\nPost reference: \(threadPost)")
            print("Replying...")

            let firstReplyReference = try await ATProtoTools().createReplyReference(from: threadPost, session: session)

            let threadPost2 = try await atProtoBluesky.createPostRecord(
                text: "I also like pancakes.",
                replyTo: firstReplyReference
            )

            print("\nPost reference: \(threadPost2)")
            print("Second reply...")

            let secondReplyReference = try await ATProtoTools().createReplyReference(from: threadPost2, session: session)

            let threadPost3 = try await atProtoBluesky.createPostRecord(
                text: "I also like ice cream.",
                replyTo: secondReplyReference
            )

            print("\nPost reference: \(threadPost3)")

        } catch {
            throw error
        }
```

It took longer than expected, but only because I literally did not feel comfortable giving you a half-assed solution. `ATProtoBluesky needs to be convenient and half-assed solutions violates that.

**Comment by MasterJ93** [comment]
The update is live. I've tested it and it seems to be resolved. Please feel free to close the issue if this is also working for you.

I apologize for being stubborn, but I want to make sure this library works for everyone who wants to use it. Please let me know if there are any other issues and thanks again for your interest, and contributions.

**Comment by aaronvegh** [comment]
Phenomenal! I’ll take a look tomorrow. Thank you! 🙏

**Comment by MasterJ93** [comment]
Were you able to test it out to see if it's working properly?

**Comment by aaronvegh** [comment]
I'm sorry I wasn't able to test it yesterday. Hoping to have time tonight! Will get back to you ASAP, I really appreciate your efforts!

**Comment by aaronvegh** [comment]
It's working perfectly! Thanks for this! 🌈
