### ISSUE TITLE
[Bug]: Bluesky User Search Results Fail When Only One Result

### ISSUE THREAD

**Issue by aaronvegh** [MasterJ93/ATProtoKit#39]
### Summary

When a user search result returns only one user, the server data fails to decode.

### Reproduction Steps

When firing a request such as `let results = try await atProtoKit.searchUsers(by: term)`, when the term returns only one match (you can try this with "aaronvegh"), the search apparently yields no result. That's because the serialization of the returned data fails: the data isn't formatted as expected.

### Expected Results

I'd expect even a single result to be returned and decoded successfully.

### Actual Results

No results, and the console shows an error related to a missing property "cursor".

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

macOS and Xcode...

### ATProtoKit Version

0.18.4

### Additional Context

AppBskyActorSearchActors.swift: 21 shows the `cursor` property as a non-optional value, even as the comment above says it is optional. If this were actually made an optional, then the query would work as expected. 

When Bluesky returns a single search result, it does not include the `cursor` property.

**Comment by MasterJ93** [comment]
That... is my fault. Sorry. 😅

I'll get that fixed before the end of the day.

Hopefully, once I complete the lexicon generator, silly mistakes like this won't appear.

**Comment by MasterJ93** [comment]
Update has been released. Testing shows that it's working without any issues. I'll be closing the issue, but if it's still a problem, please re-open the issue.

**Comment by aaronvegh** [comment]
Nope, you nailed it! Thanks so much again!
