### ISSUE TITLE
[Bug]: PDSUrl Becomes JWT During `resolveHandle`

### ISSUE THREAD

**Issue by aaronvegh** [MasterJ93/ATProtoKit#45]
### Summary

When resolving user handles during posting, the `resolveHandle` makes a request to a `pdfUrl` that is a JWT instead of the expected domain name (ie "bsky.social").

### Reproduction Steps

1. Post a message with an @-mention such as "@aaronvegh.bsky.social"
2. Note that the request to resolve the handle (in `ResolveHandle.swift`) throws an error.
3. Breaking in the function reveals the pdsUrl is a JWT instead of the expected "bsky.social".

I am completely baffled by this. I was hoping to determine what exactly is going on but I've had no luck debugging. 

### Expected Results

I was hoping to get back a properly-resolved user 

### Actual Results

The function throws an error, and the user mention is passed through the post as plain text.

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS, Other

### Operating System Version

Macos 15.0, Xcode 16, iOS 18

### ATProtoKit Version

0.20.0

### Additional Context

I place a breakpoint on `ResolveHandle.swift:45` and yield this output:

> (lldb) po pdsURL
▿ Optional<String>
  - some : "eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJFUzI1NksifQ.eyJzY29wZSI6ImNvbS5hdHByb3RvLmFjY2VzcyIsInN1YiI6ImRpZDpwbGM6dmVwaXMyYmxscnlpdHFza2phNWZtd2l3IiwiaWF0IjoxNzMwMjQ2NjkzLCJleHAiOjE3MzAyNTM4OTMsImF1ZCI6ImRpZDp3ZWI6bG9ic3Rlci51cy1lYXN0Lmhvc3QuYnNreS5uZXR3b3JrIn0.n2iq-l_s9FGtfXoYhthguijQqwtGEQ-78GAeYIDn8u6FgBiA4JOwH4aqNUKRx7Xk6NMNnK0qMbMOzkbElybzPw"

WAT. That request doesn't even fire:

> Task <61A88A3C-899D-482E-B630-C721F9FCA08C>.<2> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJFUzI1NksifQ.eyJzY29wZSI6ImNvbS5hdHByb3RvLmFjY2VzcyIsInN1YiI6ImRpZDpwbGM6dmVwaXMyYmxscnlpdHFza2phNWZtd2l3IiwiaWF0IjoxNzMwMjQ2NjkzLCJleHAiOjE3MzAyNTM4OTMsImF1ZCI6ImRpZDp3ZWI6bG9ic3Rlci51cy1lYXN0Lmhvc3QuYnNreS5uZXR3b3JrIn0.n2iq-l_s9FGtfXoYhthguijQqwtGEQ-78GAeYIDn8u6FgBiA4JOwH4aqNUKRx7Xk6NMNnK0qMbMOzkbElybzPw/xrpc/com.atproto.identity.resolveHandle?handle=aaronvegh.bsky.social, NSErrorFailingURLKey=eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJFUzI1NksifQ.eyJzY29wZSI6ImNvbS5hdHByb3RvLmFjY2VzcyIsInN1YiI6ImRpZDpwbGM6dmVwaXMyYmxscnlpdHFza2phNWZtd2l3IiwiaWF0IjoxNzMwMjQ2NjkzLCJleHAiOjE3MzAyNTM4OTMsImF1ZCI6ImRpZDp3ZWI6bG9ic3Rlci51cy1lYXN0Lmhvc3QuYnNreS5uZXR3b3JrIn0.n2iq-l_s9FGtfXoYhthguijQqwtGEQ-78GAeYIDn8u6FgBiA4JOwH4aqNUKRx7Xk6NMNnK0qMbMOzkbElybzPw/xrpc/com.atproto.identity.resolveHandle?handle=aaronvegh.bsky.social, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <61A88A3C-899D-482E-B630-C721F9FCA08C>.<2>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <61A88A3C-899D-482E-B630-C721F9FCA08C>.<2>, NSUnderlyingError=0x600000d155f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}}

I breakpoint at the earlier step in my own code to determine the pdsURL and I get a correct value there: `bsky.social`. So sometime between my initializing the framework and this call, that value is being altered.

**Comment by aaronvegh** [comment]
I tracked it down. `CreatePostRecord.swft:99`:

`facets: await ATFacetParser.parseFacets(from: postText, pdsURL: session.accessToken),`

I'll post a PR.

**Comment by MasterJ93** [comment]
It looks like it's working now. I'm closing this issue, but if it persists, please re-open it.
