### ISSUE TITLE
[Bug]: describeFeedGenerator produce not valid JSON

### ISSUE THREAD

**Issue by valvoline** [MasterJ93/ATProtoKit#48]
### Summary

describeFeedGenerator produce not valid JSON

### Reproduction Steps

```swift
        do {
            let feedDescription = try await atProto.describeFeedGenerator()
            print(feedDescription)
        } catch {
            print(error)
        }
```

### Expected Results

Description of feed generator

### Actual Results

dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character '<' around line 1, column 1." UserInfo={NSDebugDescription=Unexpected character '<' around line 1, column 1., NSJSONSerializationErrorIndex=0})))

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

14.6.1 (23G93)

### ATProtoKit Version

0.19.2

**Comment by MasterJ93** [comment]
Sorry about that; I'm unsure how I didn't see this issue until now.

I'll look at it in the morning, but at a quick glance, I may have made a mistake in the applicable struct. I'll look into what it is. It won't be available in time for version 0.20.0, though (probably a 0.20.1 update, however).

**Comment by MasterJ93** [comment]
Sorry for the long wait: there are so many bugs that I need to fix with this project.

The `develop` branch should have a for this now. Please let me know if you're still experiencing any issues with that.

**Comment by MasterJ93** [comment]
It looks like the issue is no longer here. I'll be closing the issue now, but re-open it if the issue persists.
