### ISSUE TITLE
[Bug]: EmbedViewUnion type mismatch 

### ISSUE THREAD

**Issue by bseales** [MasterJ93/ATProtoKit#50]
### Summary

When calling `getTimeline()`, there is an unknown EmbedViewUnion type, I believe it is Feed.

### Reproduction Steps

Bug was found when calling `getTimeline()`, but reproduction could be dependent on the items currently in the timeline. 

### Expected Results

Library to have a type for Feed

### Actual Results

No type for Feed.

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

iOS 18.0.1 - iPhone 12 Pro Max

### ATProtoKit Version

0.19.2

### Additional Context

Error fetching feed: typeMismatch(ATProtoKit.ATUnion.EmbedViewUnion, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "feed", intValue: nil), _CodingKey(stringValue: "Index 7", intValue: 7), CodingKeys(stringValue: "post", intValue: nil), CodingKeys(stringValue: "embed", intValue: nil)], debugDescription: "Unknown EmbedViewUnion type", underlyingError: nil))

**Comment by bseales** [comment]
Example post I believe is causing the issue:

https://bsky.app/profile/steinmakesgames.bsky.social/post/3lbg5ywcv322o

**Comment by MasterJ93** [comment]
It looks like this issue no longer exists, so I'll be closing this now. If it persists, however, please re-open the issue with the new error messages and JSON.
