### ISSUE TITLE
[Bug]: VersionNumberPluginExec Errors

### ISSUE THREAD

**Issue by aaronvegh** [MasterJ93/ATProtoKit#54]
### Summary

ATProtoKit doesn't build from the develop branch because of these errors

### Reproduction Steps

Add ATProtoKit's `develop` branch to the project. Build. See these errors in `VersionNumberPluginExec/main`:

on line 16, the error:

> 'init(filePath:directoryHint:relativeTo:)' is only available in iOS 16.0 or newer

and line 34, the error:

> Cannot find 'Process' in scope

### Expected Results

No errors

### Actual Results

The errors

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

macOS 15.1

### ATProtoKit Version

develop branch

**Comment by MasterJ93** [comment]
Could you check to see if the issue with line 16 is still giving you problems in the meantime? I've pushed an update into `develop` with that change in place.

**Comment by aaronvegh** [comment]
@MasterJ93 Indeed, the error on line 16 is gone.

However, `Process` continues to be a problem when building for iOS, because Process is only available on macOS and Catalyst targets.

Additionally, when I build my app for Catalyst, I get additional errors:

<img width="1044" alt="Screenshot 2024-11-21 at 8 30 23 PM" src="https://github.com/user-attachments/assets/85919820-715c-43dd-aae2-4498a0e1afc0">

What is this even for? This whole class doesn't seem to be doing anything useful.

**Comment by MasterJ93** [comment]
The purpose of the plugin is to automatically grab the latest tag (since it will be the version number of the latest update) and insert it into the user agent. I've been told that certain parts of Bluesky (such as cardyb) can be used, but they would like you to put a user agent in there. It's also just a good idea to have a user agent in your client, anyway.

I'd rather not make the plugin a command plugin because it means one extra step for developers. But if it's causing this many problems,... I suppose I'll have to disable it for now until I can get it to work again.

**Comment by aaronvegh** [comment]
I wonder if it would be more appropriate for your app adopters to supply a user agent, if that's the case? I feel like sending "ATProtoKit 19.0.2" is akin to sending "URLSession" as the agent on HTTP requests. 😂 I wouldn't mind injecting my app name and version into a string in the configuration struct...

**Comment by MasterJ93** [comment]
Developers can add their own custom user agent if they wish to do so. It's just that, by default, it'll say something along the lines of `ATProtoKit/0.20.0 (iOS; 18.1)`. If the developer makes their own user agent, ` ATProtoKit/0.20.0` will always be in the end, so developers have no need to write that. You can see how I've done it in `ATProtoTools.UserAgent`. It should be put into `ATProtocolConfiguration`; there should be a `userAgent` property in there (if I didn't forget).

I _suppose_ I'm making ATProtoKit take too much responsibility, but I don't exactly know where the line is supposed to be drawn in terms of that. If that makes sense.

In any case, for now, I'll disable the plugin until I can figure out how to make it run independently of whatever operating system the client is supposed to be built on. It shouldn't be doing what you're experiencing, but unfortunately, it is, and I'll have to figure that out eventually.

**Comment by MasterJ93** [comment]
I've disabled the plugin now. Let me know if you can build the project once again, and I'm really sorry for the painful experience and long wait. Fixing bugs and putting out fires is not fun when more and more keep popping up...
