### ISSUE TITLE
[Feature Request]: Make documents available on GitHub Pages

### ISSUE THREAD

**Issue by KC-2001MS** [MasterJ93/ATProtoKit#6]
### Summary

I would like to be able to display documents as static pages so that they can be machine translated.

### Pain points

I would like to be able to view the ATProtoKit documentation in a browser so that I can easily check the documentation.
Currently, it is possible to check the documentation by building the documentation in Xcode. However, we believe that displaying documents in a browser is superior because it is platform-independent and machine translation is available.
Therefore, we would like to request the ability to build DocC on GitHub Pages.
The following repositories have already implemented this content.
[https://github.com/KC-2001MS/ATProtoKit/tree/develop](https://github.com/KC-2001MS/ATProtoKit/tree/develop)

### Considered Alternatives

Compared to the method of building with Xcode, it is superior in the following points.
- Platform independent. (Available on Windows/Linux)
- Machine translation allows you to check documentation in your native language

### Is this a breaking change?

No

### Library Examples

We have already created a documentation page for this project in the forked repository.
Please refer to the following URL
[https://iroiro.dev/ATProtoKit/documentation/atprotokit](https://iroiro.dev/ATProtoKit/documentation/atprotokit)
I would like to pull request this devlop branch.

**Comment by MasterJ93** [comment]
Thanks for your suggestion. This is a feature I'm planning on doing later down the line, but I didn't think it would be something that anyone would be interested at this current time, so I put it at a medium priority. Given what you've said, I'll make an effort to work on the DocC more so it's more organized and put it up on GitHub Pages. I hope to complete that some time within the next two weeks.

**Comment by KC-2001MS** [comment]
The sample project is created in the develop branch.
Shall I make a pull request?

**Comment by MasterJ93** [comment]
I am okay with you making that pull request for this feature.

**Comment by KC-2001MS** [comment]
We have made a pull request about Docc. If there is a problem, I will address it.
I don't do pull requests very often, so sorry if it doesn't look well done.

**Comment by MasterJ93** [comment]
Hmm... it doesn't seem to be working properly. I'm going to re-open this issue until I solve it, but all it's showing is a white image. This is a little bit frustrating.

Please note that this isn't your fault: I may have messed something up here.

**Comment by KC-2001MS** [comment]
The URL generated by swift-docc-plugin is complicated, so maybe I have the wrong URL. The following URL is displayed, so I think the build is working.
[https://masterj93.github.io/ATProtoKit/documentation/atprotokit/atprotokit/](https://masterj93.github.io/ATProtoKit/documentation/atprotokit/atprotokit/)

**Comment by MasterJ93** [comment]
Yes, when I removed the custom domain, it worked. What I'm attempting to do is getting the following link to work: https://atprotokit.cjrriley.com/ATProtoKit/documentation/atprotokit/. It appears GitHub is having some trouble with this. I'll be able to figure it out, though.

**Comment by KC-2001MS** [comment]
The reason for that URL is that I am using a custom domain in the [KC-2001MS.github.io](https://iroiro.dev/en/index.html) repository, which is changing the URL of the documentation page in the ATProtokit repository.
Therefore, the ATProtokit repository itself is not adapting the custom domain.

**Comment by KC-2001MS** [comment]
I'm not sure why, but when I set a custom domain in Github Pages in the <User Name>.github.io repository, that domain is propagated in Github Pages in other repositories.

**Comment by MasterJ93** [comment]
I'll rebuild the DocC and see if it fixes anything. If not, I have a few more ideas.

**Comment by KC-2001MS** [comment]
We can see it at the following URL. Thanks for the documentation release.
[https://cjrriley.com/documentation/atprotokit/](https://cjrriley.com/documentation/atprotokit/)

**Comment by MasterJ93** [comment]
Oh! I wasn't expecting that to happen. Okay. This is good. I'm not too sure how that happened, though. I guess in this case, typing `ATProtoKit` wasn't needed after all.

**Comment by MasterJ93** [comment]
I'll be closing this issue now. But if there's any issues, please re-open it.

Over time, the documentation will be updated with articles, re-structuring into a more organized layout, and tutorials. But this project is still pretty unstable, so I apologize in advance if things break.

I hope my project has enough value and features to create the projects you're trying to build. ☺️

**Comment by MasterJ93** [comment]
The underlying parts of the logging have been completed. I'll be adding the logs over to the other files over time. Thanks again for the suggestion. I apologize for not doing much in the project until now, I've been extremely busy with other things.

The pull request reopen and close over time until all of the places that need logs have been successfully added.
