### ISSUE TITLE
[Bug]: Rate limit info isn't decoded properly

### ISSUE THREAD

**Issue by tonyarnold** [MasterJ93/ATProtoKit#62]
### Summary

The retry after field is empty due to a header mismatch.

### Reproduction Steps

I exceeded the rate limit on my account, and started receiving errors like: 

```
Error during authentication: ATProtoKit.ATAPIError.tooManyRequests(error: ATProtoKit.ATHTTPResponseError(error: "RateLimitExceeded", message: "Rate Limit Exceeded"), retryAfter: nil)
```

### Expected Results

The `retryAfter` parameter contains a valid date and time.

### Actual Results

The `retryAfter` parameter is nil.

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

15.2 Beta (24C5089c)

### ATProtoKit Version

0.20.1

### Additional Context

It looks like the library is attempting to decode a header field name `Retry-After`, however looking at the responses from the server, the value is actually stored in `RateLimit-Reset`.

**Comment by airowe** [comment]
@tonyarnold There is no definition for `RateLimit-Reset` in [the AT Protocol docs](https://atproto.com/specs/xrpc#summary-of-http-status-codes). Can you upload a dump of the logs showing that header returned?

**Comment by airowe** [comment]
> @tonyarnold There is no definition for `RateLimit-Reset` in [the AT Protocol docs](https://atproto.com/specs/xrpc#summary-of-http-status-codes). Can you upload a dump of the logs showing that header returned?

Actually, disregard this I can push up a PR to allow for this. Looks like it's not documented but is a valid response, per this: https://github.com/bluesky-social/atproto/discussions/697

Do you need any of the other fields?

"ratelimit-limit"=>["30"],
"ratelimit-remaining"=>["0"],
"ratelimit-reset"=>["1694912614"],
"ratelimit-policy"=>["30;w=300"],

**Comment by tonyarnold** [comment]
Thanks, @airowe. For now, it would be great to have everything but the policy (as that would require more work to decode).

**Comment by MasterJ93** [comment]
Sorry, I'm not understanding: is this an issue on the AT Protocol's end or ATProtoKit's end? Because if it's the latter, then I'll look into it and fix that, but if it's the former, then unfortunately, there's nothing I can really do about it.

**Comment by tonyarnold** [comment]
It's an issue with ATProtoKit not reading the rate limit information that the AT protocol is vending. Please see @airowe's response above for links to the relevant conversation in the ATProto repo.

**Comment by MasterJ93** [comment]
Alright. I'll check that out can fix the issue.

**Comment by tonyarnold** [comment]
That's excellent, and sufficient for my immediate needs — thanks @MasterJ93! 🫶

**Comment by MasterJ93** [comment]
@tonyarnold 0.20.3 is out now, which should fix the issue with respect to the `retryAfter` field not returning anything correctly. The AT Protocol specs say to use the "Retry-After" field, but from the output, and from what's been explained by airowe, the header is actually supposed to be `ratelimit-reset`.

Please let me know if this works or not.
