### ISSUE TITLE
[Bug]: getSession cannot decode UserSession model

### ISSUE THREAD

**Issue by tonyarnold** [MasterJ93/ATProtoKit#66]
### Summary

I'm unable to use getSession, as the response from the server is different to the expected model

### Reproduction Steps

1. Use the `getSession(…)` method to restore a session.

### Expected Results

I receive a usable session that I can use with `ATProtoKit(configuration: …)`.

### Actual Results

```
Error during authentication: Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "accessJwt", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"accessJwt\", intValue: nil) (\"accessJwt\").", underlyingError: nil))
```

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

15.2 (24C98)

### ATProtoKit Version

0.20.3

### Additional Context

If you [read the response schema for the getSession endpoint](https://docs.bsky.app/docs/api/com-atproto-server-get-session), the schema does not contain the refresh or access JWTs.

**Comment by tonyarnold** [comment]
I wonder if it's worth considering forcing the user's implementation to provide the refresh and access tokens for a session?

**Comment by tonyarnold** [comment]
I've added a simple workaround for now to build a `UserSession` once I have a `SessionResponse`: 

```swift
extension ATProtocolConfiguration {
    func getUserSession(
        using sessionResponse: SessionResponse,
        accessToken: String,
        refreshToken: String,
        pdsURL: String? = nil,
        maxRetryCount: Int? = 3,
        retryTimeDelay: TimeInterval? = 1.0
    ) -> UserSession {
        return UserSession(
            handle: sessionResponse.handle,
            sessionDID: sessionResponse.sessionDID,
            email: sessionResponse.email,
            isEmailConfirmed: sessionResponse.isEmailConfirmed,
            isEmailAuthenticationFactorEnabled: sessionResponse.isEmailAuthenticationFactorEnabled,
            accessToken: accessToken,
            refreshToken: refreshToken,
            didDocument: sessionResponse.didDocument,
            isActive: sessionResponse.isActive,
            status: sessionResponse.status,
            pdsURL: pdsURL,
            maxRetryCount: maxRetryCount,
            retryTimeDelay: retryTimeDelay
        )
    }
}
```

**Comment by MasterJ93** [comment]
Please try it again with the `develop` branch to see if that issue is resolved; that update has changed how `getSession` works.

I should note that the authorization flow has changed, so please take a look at [this guide](https://github.com/MasterJ93/ATProtoKit/blob/develop/Sources/ATProtoKit/ATProtoKit.docc/Misc/0210AuthFlowChange.md) for how to migrate your code (though, it's not that long: just some tweaks to your existing code will do).

**Comment by tonyarnold** [comment]
Thanks, @MasterJ93 — I will do just that. 

Does `try await config.authenticate()` still make a call to create a session, or will it use the existing info to intelligently get a session first (assuming it has an access and refresh key)? The rate limit on the session creation endpoints is (rightly) quite small.

**Comment by MasterJ93** [comment]
`authenticate()` will always use `com.atproto.server.createSession`; I recommend using that feature conservatively. If you need to check for the access and refresh tokens, you can use `ATProtocolConfiguration.session`, which will contain these tokens. If the access token expires, however, you can use `ATProtocolConfiguration.refreshSession`, which will create a new `UserSession` object that contains a new access token.

In the future, I'll make it where it will automatically refresh the token if the API returns an error that the token has expired. This will probably be a patch update to 0.21.0.

**Comment by MasterJ93** [comment]
I've pushed the fixes to `main` and the 0.21.0 release will be out in an hour or so, so I'll be closing the issue. If it persists, however, please re-open the issue with new information.

**Comment by tonyarnold** [comment]
I've just checked out the changes on `main`, but I can't see a way for me to provide a saved access/refresh token so that I don't need to unnecessarily call authenticate. Is there currently a way to do this?

**Comment by MasterJ93** [comment]
I'll work on a fix tomorrow.

**Comment by MasterJ93** [comment]
It seems that there's no more problems, so I'm going to close this issue. If it pops up again, however, please re-open the issue and I'll see what can be done about it.
