### ISSUE TITLE
[Bug]: ATProtoKit.getAuthorFeed() doesn't seem to respect the passed in filter

### ISSUE THREAD

**Issue by akshatksharma** [MasterJ93/ATProtoKit#73]
### Summary

The ATProtoKit.getAuthorFeed() method doesn't filter posts when a non default filter (AppBskyLexicon.Feed.GetAuthorFeed.Filter) is passed in. I always get `postsWithReplies` back

### Reproduction Steps

Passed in the `.postsWithNoReplies` option for `postFilter: AppBskyLexicon.Feed.GetAuthorFeed.Filter? `
```
let myFeed = try await agent.atProtoClient.getAuthorFeed(by: handle, postFilter: .postsWithNoReplies)
```

But still received my replies
![Simulator Screenshot - iPhone 16 Pro - 2024-12-15 at 11 02 38](https://github.com/user-attachments/assets/7e81f484-72b6-4f5a-ace1-88315000988b)

Can see that some of the rows (like the pins) are not posts but replies on my profile
notakshat.bsky.social

### Expected Results

To only receive my top level posts and reposts

### Actual Results

Received my top level posts, reposts, and replies

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

iOS 18

### ATProtoKit Version

0.21.1

**Comment by MasterJ93** [comment]
Thanks. I'll investigate. It's probably a simple fix.

**Comment by MasterJ93** [comment]
Found the issue: I forgot to use `.rawValue` so it's taking the `enum` value literally. It'll be resolved in the next update (hopefully early this week).
