### ISSUE TITLE
[Bug]: getSession and refreshSession don't update the session property

### ISSUE THREAD

**Issue by tonyarnold** [MasterJ93/ATProtoKit#78]
### Summary

Calling getSession and refreshSession don't update the session property.

### Reproduction Steps

Use either method to refresh or get your session using access/refresh tokens.

### Expected Results

Afterward, the `session` property is updated, and subsequent requests are properly authenticated.

### Actual Results

The `session` property is not modified by getSession or refreshSession, meaning subsequent requests are not authenticated.

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

15.2 (24C101)

### ATProtoKit Version

main

**Comment by tonyarnold** [comment]
Actually, has this been handled by 739254e?

**Comment by MasterJ93** [comment]
I'll look into it with respect to `refreshSession`. `getSession` will be a tiny bit more tricky, since the response to the request will pretty much be the same (unless the token was revoked, expired, or nonexistent), but I'll see what I can do there.

As for your question, yes: the helper methods of that commit is used to update create a new `UserSession` object in `ATProtocolConfiguration.session`. Is it still not working? I made sure they were tested to work properly...

**Comment by tonyarnold** [comment]
> Is it still not working? I made sure they were tested to work properly

I apologise — I filed this before I saw that a lot of work had been done this week. Filing this issue was sitting on my to do list since our conversation on Discord earlier in the week — I only had time for it yesterday.

**Comment by MasterJ93** [comment]
It's fine. For now, I'm going to close the issue, but if it doesn't work, then please re-open the issue and I'll look into it.

That said, when it comes to `getSession` specifically, I'm struggling to understand _why_ it should update `ATProtocolConfiguration.session`. When you want to get that session, you need the access token. When the response is made, it doesn't give you a ton of information, and rarely does it ever change (this isn't a limitation with my library, but with how that request works in the AT Protocol). Could you explain to me what the use case would be for it to change (save for if the token(s) is/has expired/revoked)? I guess there's a disconnect with respect to what I'm understanding.

**Comment by tonyarnold** [comment]
> I guess there's a disconnect with respect to what I'm understanding.

No, I doubt that! 

So maybe my thinking is not correct? My thought process was that on making a request:

1. Try with the access token we have (is this `getSession(…)`?). If _that_ fails:
2. Use the refresh token to refresh the access token, and use the updated access token (which _would_ update the local user session). If _that_ fails:
3. Authenticate and retrieve a new refresh/access token pair and use _that_ access token (and update the local user session).

So perhaps `getSession(…)` updating the user session is pointless? 🤔
